keys:
  - &host 7ED71373082E0FE0F90239710233D0893BBB9872
  - &kokev age1g0xdesgjx73yjljvsuvwtpu6uftec0a2w2mgkj5r5uc6tpsnvswsn2yewg
  - &laptop age15ueqpwexzkjwg43kc9kjjxg5s32668ehldj3e94l4r6ggsf74vgsmffjg3
creation_rules:
  - path_regex: secrets/kokev/.*.(yaml|yml)
    pgp: *host
    age: *kokev
  - path_regex: secrets/kevin-laptop/.*.(yaml|yml)
    pgp: *host
    age: *laptop
  - path_regex: secrets/*/.*.(yaml|yml)
    pgp: *host
