# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
let
  btrfsOptions = [
    "noatime"
    "compress-force=zstd:3"
    "ssd"
    "space_cache=v2"
  ];
in

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    tmp = {
      useTmpfs = true;
    };
    kernel = {
      sysctl = {
        "kernel.unprivileged_userns_clone" = 1;
      };
    };
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "ahci"
        "nvme"
        "usbhid"
      ];
      kernelModules = [ ];
      luks.devices."nvme_crypt".device = "/dev/disk/by-uuid/20fa87a6-78c0-4aea-b2a6-8e70f3238a60";
    };
    kernelPackages = pkgs.linuxPackages_zen;
    extraModulePackages = with config.boot.kernelPackages; [
      # Required for fan control
      nct6687d
    ];

    kernelModules = [
      "kvm-intel"
      "nct6687"
    ];
  };

  fileSystems = {
    "/" = {
      device = "/dev/mapper/nvme_crypt";
      fsType = "btrfs";
      options = [ "subvol=@root_nix" ] ++ btrfsOptions;
    };
    "/.snapshots" = {
      device = "/dev/mapper/nvme_crypt";
      fsType = "btrfs";
      options = [ "subvol=@snapshots_root_nix" ] ++ btrfsOptions;

    };

    "/home" = {
      device = "/dev/mapper/nvme_crypt";
      fsType = "btrfs";
      options = [ "subvol=@home" ] ++ btrfsOptions;
    };
    "/home/.snapshots" = {
      device = "/dev/mapper/nvme_crypt";
      fsType = "btrfs";
      options = [ "subvol=@snapshots_home" ] ++ btrfsOptions;
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/a3326aac-19f0-4e83-ad6f-a03c7c3af4b2";
      fsType = "btrfs";
      options = btrfsOptions;
    };

    "/boot/efi" = {
      device = "/dev/disk/by-uuid/A7C9-5013";
    };

    "/mnt/nvme_storage" = {
      device = "/dev/disk/by-uuid/60cabdaa-549f-410b-9110-7de8563dc9bd";
      fsType = "btrfs";
      options = [ "subvol=@data" ] ++ btrfsOptions;
    };
    "/mnt/nvme_storage/.snapshots" = {
      device = "/dev/disk/by-uuid/60cabdaa-549f-410b-9110-7de8563dc9bd";
      fsType = "btrfs";
      options = [ "subvol=@snapshots_data" ] ++ btrfsOptions;
    };

    "/home/kevin/Bilder" = {
      device = "/mnt/nvme_storage/home/Bilder";
      options = [ "bind" ];
    };
    "/home/kevin/syncthing" = {
      device = "/mnt/nvme_storage/home/syncthing";
      options = [ "bind" ];
    };
    "/home/kevin/Videos" = {
      device = "/mnt/nvme_storage/home/Videos";
      options = [ "bind" ];
    };
    "/home/kevin/Dokumente" = {
      device = "/mnt/nvme_storage/home/Dokumente";
      options = [ "bind" ];
    };
    "/home/kevin/Games" = {
      device = "/mnt/nvme_storage/home/Games";
      options = [ "bind" ];
    };
  };

  environment.etc.crypttab = {
    mode = "0600";
    text = ''
      # <volume-name> <encrypted-device> [key-file] [options]
      nvme1-crypt UUID=3351d105-c483-47f7-b63b-888e637754d4 /root/nvme-key nofail
    '';
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware = {
    cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    graphics = {
      enable = true;
      extraPackages = with pkgs; [
        intel-media-driver # For Broadwell (2014) or newer processors. LIBVA_DRIVER_NAME=iHD
      ];
    };
  };
}
