# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  environment.systemPackages = with pkgs; [
    linuxKernel.packages.linux_zen.nct6687d
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [
    "kvm-intel"
    "nct6687"
  ];
  boot.extraModulePackages = with config.boot.kernelPackages; [
    # Required for fan control
    nct6687d
  ];

  fileSystems."/" = {
    device = "/dev/mapper/nvme_crypt";
    fsType = "btrfs";
    options = [ "subvol=@root_nix" ];
  };
  # TODO: snapshot mounts

  fileSystems."/home" = {
    device = "/dev/mapper/nvme_crypt";
    fsType = "btrfs";
    options = [ "subvol=@home" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/a3326aac-19f0-4e83-ad6f-a03c7c3af4b2";
    fsType = "btrfs";
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/A7C9-5013";
  };

  fileSystems."/mnt/nvme_storage" = {
    device = "/dev/disk/by-uuid/60cabdaa-549f-410b-9110-7de8563dc9bd";
    fsType = "btrfs";
    options = [ "subvol=@data" ];
  };

  fileSystems."/home/kevin/Bilder" = {
    device = "/mnt/nvme_storage/home/Bilder";
    options = [ "bind" ];
  };
  fileSystems."/home/kevin/syncthing" = {
    device = "/mnt/nvme_storage/home/syncthing";
    options = [ "bind" ];
  };
  fileSystems."/home/kevin/Videos" = {
    device = "/mnt/nvme_storage/home/Videos";
    options = [ "bind" ];
  };
  fileSystems."/home/kevin/Dokumente" = {
    device = "/mnt/nvme_storage/home/Dokumente";
    options = [ "bind" ];
  };
  fileSystems."/home/kevin/Games" = {
    device = "/mnt/nvme_storage/home/Games";
    options = [ "bind" ];
  };

  boot.initrd.luks.devices."nvme_crypt".device =
    "/dev/disk/by-uuid/20fa87a6-78c0-4aea-b2a6-8e70f3238a60";

  environment.etc.crypttab = {
    mode = "0600";
    text = ''
      # <volume-name> <encrypted-device> [key-file] [options]
      nvme1-crypt UUID=3351d105-c483-47f7-b63b-888e637754d4 /root/nvme-key nofail
    '';
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
