# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
_: {
  flake.modules.nixos.rpi-drucker = _: {
    # Quick (and probably wrong) Nix on Rpi Boot:
    # 1. GPU loads bootcode.bin /firmware
    # 2. Starts u-boot (via kernel.img?) /firmware
    # 3. Loads entry /
    # 3. Boots actual kernel from /
    # Build sd image with nixos-rebuild build-image --image-variant sd-card --flake .#rpi-drucker
    boot = {
      zfs.forceImportRoot = false;
      initrd = {
        availableKernelModules = [
          "xhci_pci"
          "usbhid"
        ];
        kernelModules = [ ];
      };
      kernelModules = [ ];
      extraModulePackages = [ ];
    };

    boot.loader = {
      grub.enable = false;
      generic-extlinux-compatible.enable = true;
    };
    fileSystems."/" = {
      device = "/dev/disk/by-label/NIXOS_SD"; # this is important!
      fsType = "ext4";
      options = [ "noatime" ];
    };
  };
}
