# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  settings,
  ...
}:
let
  btrfsOptions = [
    "noatime"
    "compress-force=zstd:3"
    "ssd"
    "space_cache=v2"
  ];
in

{
  boot.loader.raspberryPi.bootloader = "kernel";
  hardware.raspberry-pi.config = {
    all = {
      options = {
        gpu_mem = {
          enable = lib.mkDefault true;
          value = lib.mkDefault 16;
        };
      };
    };
  };
  system.nixos.tags =
    let
      cfg = config.boot.loader.raspberryPi;
    in
    [
      "raspberry-pi-${cfg.variant}"
      cfg.bootloader
      config.boot.kernelPackages.kernel.version
    ];

  fileSystems = {
    "/" = {
      device = "/dev/mapper/nvme_crypt";
      fsType = "btrfs";
      options = [ "subvol=@root_nix" ] ++ btrfsOptions;
    };
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
