# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  ...
}:
{
  boot.loader.raspberryPi.bootloader = "kernel";
  fileSystems = {
    "/boot" = {
      device = "/dev/mmcblk0p1";
      options = [ "noatime" ];
    };
    "/" = {
      device = "/dev/mmcblk0p2";
      options = [ "noatime" ];
    };
  };
  hardware.raspberry-pi.config = {
    all = {
      options = {
        gpu_mem = {
          enable = lib.mkDefault true;
          value = lib.mkDefault 16;
        };
      };
    };
  };
  system.nixos.tags =
    let
      cfg = config.boot.loader.raspberryPi;
    in
    [
      "raspberry-pi-${cfg.variant}"
      cfg.bootloader
      config.boot.kernelPackages.kernel.version
    ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
