# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  settings,
  ...
}:
let
  btrfsOptions = [
    "noatime"
    "compress-force=zstd:3"
    "ssd"
    "space_cache=v2"
  ];
in

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")

  ];
  system.nixos.tags =
    let
      cfg = config.boot.loader.raspberryPi;
    in
    [
      "raspberry-pi-${cfg.variant}"
      cfg.bootloader
      config.boot.kernelPackages.kernel.version
    ];

  boot = {
    tmp = {
      useTmpfs = true;
    };
  };

  fileSystems = {
    "/" = {
      device = "/dev/mapper/nvme_crypt";
      fsType = "btrfs";
      options = [ "subvol=@root_nix" ] ++ btrfsOptions;
    };
    "/.snapshots" = {
      device = "/dev/mapper/nvme_crypt";
      fsType = "btrfs";
      options = [ "subvol=@snapshots_root_nix" ] ++ btrfsOptions;

    };

    "/home" = {
      device = "/dev/mapper/nvme_crypt";
      fsType = "btrfs";
      options = [ "subvol=@home" ] ++ btrfsOptions;
    };
    "/home/.snapshots" = {
      device = "/dev/mapper/nvme_crypt";
      fsType = "btrfs";
      options = [ "subvol=@snapshots_home" ] ++ btrfsOptions;
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/a3326aac-19f0-4e83-ad6f-a03c7c3af4b2";
      fsType = "btrfs";
      options = btrfsOptions;
    };

    "/boot/efi" = {
      device = "/dev/disk/by-uuid/A7C9-5013";
    };

    "/mnt/nvme_storage" = {
      device = "/dev/disk/by-uuid/60cabdaa-549f-410b-9110-7de8563dc9bd";
      fsType = "btrfs";
      options = [ "subvol=@data" ] ++ btrfsOptions;
    };
    "/mnt/nvme_storage/.snapshots" = {
      device = "/dev/disk/by-uuid/60cabdaa-549f-410b-9110-7de8563dc9bd";
      fsType = "btrfs";
      options = [ "subvol=@snapshots_data" ] ++ btrfsOptions;
    };

    "/home/kevin/Bilder" = {
      device = "/mnt/nvme_storage/home/Bilder";
      options = [ "bind" ];
    };
    "/home/kevin/syncthing" = {
      device = "/mnt/nvme_storage/home/syncthing";
      options = [ "bind" ];
    };
    "/home/kevin/Videos" = {
      device = "/mnt/nvme_storage/home/Videos";
      options = [ "bind" ];
    };
    "/home/kevin/Dokumente" = {
      device = "/mnt/nvme_storage/home/Dokumente";
      options = [ "bind" ];
    };
    "/home/kevin/Games" = {
      device = "/mnt/nvme_storage/home/Games";
      options = [ "bind" ];
    };
  };

  environment.etc.crypttab = {
    mode = "0600";
    text = ''
      # <volume-name> <encrypted-device> [key-file] [options]
      nvme1-crypt UUID=3351d105-c483-47f7-b63b-888e637754d4 /root/nvme-key nofail
    '';
  };

  swapDevices = [ ];

  #nixpkgs.hostPlatform = lib.mkDefault settings.architecture;
}
