# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
let
  btrfsOptions = [
    "noatime"
    "compress-force=zstd:3"
    "ssd"
    "space_cache=v2"
  ];
in

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    tmp = {
      useTmpfs = true;
    };
    kernel = {
      sysctl = {
        "kernel.unprivileged_userns_clone" = 1;
      };
    };
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "ahci"
        "nvme"
        "usbhid"
      ];
      kernelModules = [ ];
      luks.devices."ssd_crypt".device = "/dev/sda3";
    };
    kernelPackages = pkgs.linuxPackages_zen;

    kernelModules = [
      "kvm-intel"
    ];
  };

  fileSystems =
    let
      root_device = "/dev/mapper/ssd_arch-root";
    in
    {
      "/" = {
        device = root_device;
        fsType = "btrfs";
        options = [ "subvol=@root" ] ++ btrfsOptions;
      };
      "/nix" = {
        device = root_device;
        fsType = "btrfs";
        options = [ "subvol=@nix" ] ++ btrfsOptions;
      };
      "/.snapshots" = {
        device = root_device;
        fsType = "btrfs";
        options = [ "subvol=@snapshots_root" ] ++ btrfsOptions;

      };

      "/home" = {
        device = root_device;
        fsType = "btrfs";
        options = [ "subvol=@home" ] ++ btrfsOptions;
      };
      "/home/.snapshots" = {
        device = root_device;
        fsType = "btrfs";
        options = [ "subvol=@snapshots_home" ] ++ btrfsOptions;
      };

      "/boot" = {
        device = "/dev/sda1";
        fsType = "ext4";
      };

    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
