name: Build
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          #- runs-on: ubuntu-24.04
          #  hosts:
          #    - kevin-nix
          - runs-on: ubuntu-24.04-arm
            hosts:
              - rpi-drucker
    steps:
    - uses: actions/checkout@v5
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: debloat
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo rm -rf /opt/microsoft
        sudo rm -rf /usr/lib/llvm-*
        sudo rm -rf /usr/local/julia*
        sudo rm -rf /usr/local/share/chromium
        sudo rm -rf /usr/local/share/powershell
        sudo rm -rf /usr/share/swift
        sudo rm -rf /opt/ghc \
          /opt/google/chrome \
          /opt/pipx \
          /usr/lib/mono \
          /usr/local/lib/android \
          /usr/local/lib/node_modules
        sudo df -TBG /
    # There has to be a better way with github?
    - run: |
        # RLY Github? :O
        configs=$(echo '${{ toJSON(matrix.platform.hosts) }}' | jq -r '.[]')
        echo "Hosts: $configs"
        for config in "${configs}"; do
          nix run nixpkgs#nixos-rebuild -- --flake .#${config} build
        done
