name: Build
on:
  push:
jobs:
  build-nixos:
    strategy:
      matrix:
        host:
          - kevin-nix
          - kevin-laptop
          - kokev
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - &install-nix
      uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - &debloat
      name: debloat
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo rm -rf /opt/microsoft
        sudo rm -rf /usr/lib/llvm-*
        sudo rm -rf /usr/local/julia*
        sudo rm -rf /usr/local/share/chromium
        sudo rm -rf /usr/local/share/powershell
        sudo rm -rf /usr/share/swift
        sudo rm -rf /opt/ghc \
          /opt/google/chrome \
          /opt/pipx \
          /usr/lib/mono \
          /usr/local/lib/android \
          /usr/local/lib/node_modules
        sudo df -TBG /
    - run: nix run nixpkgs#nixos-rebuild -- --flake .#${{ matrix.host }} build
  build-home-manager:
    strategy:
      matrix:
        host:
          - kevin@kevin-nix
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - *install-nix
    - *debloat
    - run: nix run nixpkgs#home-manager -- --flake .#${{ matrix.host }} build
